[package]
name = "geminiscraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unqlite = "1.5.0"
gmi = "0.2.1"
log = "0.4"
stderrlog = "0.5.3"
threadpool = "1.8.1"
crossbeam-channel = "0.5.6"
